version: '3.8'

services:
  certconverter:
    image: alpine/openssl:latest
    container_name: ${COMPOSE_PROJECT_NAME}-cert-converter
    volumes:
      - ${CERTS_PATH:-certificates}:/certificates
    networks:
      - iot
    working_dir: /certificates/live/${WEB_SERVICE_HOSTNAME}
    command: pkcs12 -export -in fullchain.pem -inkey privkey.pem -out keystore.p12 -name tomcat -CAfile chain.pem -caname root -passout pass:${CERT_KEY_STORE_PASSWORD} 

volumes:
  certificates: {}

networks:
  iot: {}
