version: '3.8'

services:
  certgenerator:
    image: certbot/certbot:latest
    container_name: ${COMPOSE_PROJECT_NAME}-cert-generator
    ports:
      - 80:80
    volumes:
      - ${CERTS_PATH:-certificates}:/etc/letsencrypt
    networks:
      - cert
    command: certonly --agree-tos --email ${CERT_RENEW_EMAIL} --non-interactive --standalone --preferred-challenges http -d ${WEB_SERVICE_HOSTNAME}

  certconverter:
    image: alpine/openssl:latest
    container_name: ${COMPOSE_PROJECT_NAME}-cert-converter
    volumes:
      - ${CERTS_PATH:-certificates}:/certificates
    networks:
      - cert
    working_dir: /certificates/live/${WEB_SERVICE_HOSTNAME}
    command: pkcs12 -export -in fullchain.pem -inkey privkey.pem -out keystore.p12 -name tomcat -CAfile chain.pem -caname root -passout pass:${CERT_KEY_STORE_PASSWORD}

volumes:
  certificates: {}

networks:
  cert: {}
