FROM maven:3.8-openjdk-17 AS build
ARG SERVICE_ACCOUNT_JSON_PATH
COPY src /app/src
COPY pom.xml /app
COPY $SERVICE_ACCOUNT_JSON_PATH /app/src/main/resources/serviceAccount.json
RUN mvn -f /app/pom.xml clean package -Dmaven.test.skip

FROM gcr.io/distroless/java17:latest
ARG WEB_SERVICE_HOSTNAME
ARG API_KEY
ARG CERT_KEY_STORE_PASSWORD
ENV WEB_SERVICE_HOSTNAME=$WEB_SERVICE_HOSTNAME
ENV API_KEY=$API_KEY
ENV CERT_KEY_STORE_PASSWORD=$CERT_KEY_STORE_PASSWORD
COPY --from=build /app/target/iot-noise-detection-backend-1.0.0.jar /app/iot-noise-detection-backend-1.0.0.jar
ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=prod","/app/iot-noise-detection-backend-1.0.0.jar"]
