FROM maven:3.8-openjdk-17 AS build
COPY src /app/src
COPY pom.xml /app
RUN mvn -f /app/pom.xml clean package -Dmaven.test.skip

FROM gcr.io/distroless/java17:latest
COPY --from=build /app/target/iot-noise-detection-backend-0.0.1-SNAPSHOT.jar /app/iot-noise-detection-backend-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/app/iot-noise-detection-backend-0.0.1-SNAPSHOT.jar"]