FROM maven:3.8-openjdk-17 AS build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package -Dmaven.test.skip

FROM gcr.io/distroless/java17:latest
COPY --from=build /usr/src/app/target/iot-noise-detection-backend-0.0.1-SNAPSHOT.jar /usr/app/iot-noise-detection-backend-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/usr/app/iot-noise-detection-backend-0.0.1-SNAPSHOT.jar"]