server:
  port: 443
  baseURL: "https://iot.alexroyle.com/"
#  ssl:
#   key-store: C:/Certbot/live/iot.alexroyle.com/keystore.p12
#    key-store-password: ""
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    static-locations: classpath:/public/
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/iot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
