server:
  port: 80
  baseURL: "http://localhost/"
  apiKey: "developmentKey"
spring:
  profiles:
    active: ${activatedProperties}
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    static-locations: classpath:/public/
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/iot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
