server:
  port: 443
  baseURL: "https://${WEB_SERVICE_HOSTNAME}/"
  ssl:
   key-store: /app/certificates/live/${WEB_SERVICE_HOSTNAME}/keystore.p12
   key-store-password: "${CERT_KEY_STORE_PASSWORD}"
  keyStoreType: PKCS12
  keyAlias: tomcat
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    static-locations: classpath:/public/
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://database:3306/iot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
