---
name: Lint and Test

#####################################################
# Start the job on all pull request and main pushes #
#####################################################
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

###############
# Set the Job #
###############
jobs:
  ################################
  # Run ESLint against code base #
  ################################
  es-lint:
    # Name the Job
    name: ESLint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      ##########################
      # Setup node environment #
      ##########################
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      #####################################
      # Install project node dependencies #
      #####################################
      - name: Install project dependencies
        run: yarn
      - name: Install project firebase functions dependencies
        run: yarn --cwd ./functions/
      ########
      # Lint #
      ########
      - name: Run lint script on web app
        run: yarn lint
      - name: Run lint script on firebase functions
        run: yarn --cwd ./functions/ lint
  ###############################
  # Run tests against code base #
  ###############################
  test:
    # Name the Job
    name: Test Code Base
    # Wait for specified jobs
    needs: [es-lint]
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      ##########################
      # Setup node environment #
      ##########################
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      #####################################
      # Install project node dependencies #
      #####################################
      - name: Install project dependencies
        run: yarn
      ########
      # Test #
      ########
      - name: Run unit test script
        run: yarn test:unit
      # - name: Run end to end test script
      #   run: yarn test:e2e:ci
      ###################
      # Attempt a build #
      ###################
      - name: Run build script to check it builds
        run: yarn build
